### ISSUE TITLE
Support for serverless driver over HTTP on Prisma

### ISSUE THREAD

**Issue by destroyer22719** [neondatabase/serverless#125]
Hello,

I was wondering if we can use the serverless driver over HTTP in prisma, https://neon.tech/docs/serverless/serverless-driver#use-the-driver-over-http

I know you can do it through web sockets but for my application I was looking to do it just over http but I don't need it over web sockets. I've been reading the documentation but I can't seem to find much on it for Prisma

**Comment by rishi-raj-jain** [comment]
We recently updated https://neon.tech/docs/guides/prisma to mention about the same.

![Image](https://github.com/user-attachments/assets/321cf717-073d-485d-b8aa-aff1c2429f24)

**Comment by jawj** [comment]
Thanks @rishi-raj-jain. 

That's a fine way to do it. Just make sure you only use `pool.query()`, not `pool.connect()`, and don't set any listeners on the pool object — `'error' | 'connect' | 'acquire' | 'release' | 'remove'` — which will prevent it from sending queries via http `fetch`.

You should then not need to set the `webSocketConstructor` option (and indeed some platforms may complain if you try).

I also checked with Prisma, and the other option here is to import `PrismaNeonHTTP` instead of `PrismaNeon` from `@prisma/adapter-neon`.

However, they warn: "It’s not documented because it’s not recommended for production usage and isn’t tested much because it doesn’t support transactions. It should be fine for reads or trivial queries but it will break with more complex queries, especially with writes. Data consistency is not a risk because it will actually throw an error whenever Prisma tries to open a transaction internally and will fail to execute the query, so we didn’t go to great lengths to hide or remove it. It has some users successfully using it (I recently merged a PR from one of them) but it’s not in a state where we can recommend using it or advertise it to a wide audience of users."
