### ISSUE TITLE
Should the `neon` function take a pooled or unpooled connection string?

### ISSUE THREAD

**Issue by benkingcode** [neondatabase/serverless#91]
Since it's a one-shot should it use the pooled connection string or unpooled? Documentation is not clear on this. Thanks!

**Comment by jawj** [comment]
Sorry for the slow reply on this.

The `neon` function provides http-based queries. Connection pooling for these is provided on the back-end independent of pgBouncer, so it's best to provide the **unpooled** connection string here. We plan to treat all connection strings as unpooled connection strings for this purpose in the near future, so that it won't matter. But in the meantime, the **unpooled** connection string is best.

Note that for connection strings passed to `new Client()` or `new Pool()`, where queries will be sent over WebSockets, the situation is different. There, the [ordinary pooled vs unpooled considerations](https://neon.tech/docs/connect/connection-pooling) apply.
